### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Binteislam** [bert-nmt/bert-nmt#17]
I have encountered the following error while trying to train bert fused nmt using BERT-Base, Multilingual Cased. Kindly help!

`File "/mnt/beegfs/home/abdulrauf/alector/nrpu-July/installations/bert-nmt/train.py", line 315, in <module>
    cli_main()
  File "/mnt/beegfs/home/abdulrauf/alector/nrpu-July/installations/bert-nmt/train.py", line 311, in cli_main
    main(args)
  File "/mnt/beegfs/home/abdulrauf/alector/nrpu-July/installations/bert-nmt/train.py", line 89, in main
    train(args, trainer, task, epoch_itr)
  File "/mnt/beegfs/home/abdulrauf/alector/nrpu-July/installations/bert-nmt/train.py", line 130, in train
    log_output = trainer.train_step(samples)
  File "/mnt/beegfs/projects/alector/nrpu-July/installations/bert-nmt/fairseq/trainer.py", line 289, in train_step
    raise e
  File "/mnt/beegfs/projects/alector/nrpu-July/installations/bert-nmt/fairseq/trainer.py", line 266, in train_step
    ignore_grad
  File "/mnt/beegfs/projects/alector/nrpu-July/installations/bert-nmt/fairseq/tasks/fairseq_task.py", line 232, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/mnt/beegfs/home/abdulrauf/miniconda/envs/bertNMT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/beegfs/projects/alector/nrpu-July/installations/bert-nmt/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
    net_output = model(**sample['net_input'])
  File "/mnt/beegfs/home/abdulrauf/miniconda/envs/bertNMT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/beegfs/projects/alector/nrpu-July/installations/bert-nmt/fairseq/models/fairseq_model.py", line 241, in forward
    bert_encoder_out, _ =  self.bert_encoder(bert_input, output_all_encoded_layers=True, attention_mask= 1. - bert_encoder_padding_mask)
  File "/mnt/beegfs/home/abdulrauf/miniconda/envs/bertNMT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/beegfs/projects/alector/nrpu-July/installations/bert-nmt/bert/modeling.py", line 736, in forward
    embedding_output = self.embeddings(input_ids, token_type_ids)
  File "/mnt/beegfs/home/abdulrauf/miniconda/envs/bertNMT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/beegfs/projects/alector/nrpu-July/installations/bert-nmt/bert/modeling.py", line 272, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/mnt/beegfs/home/abdulrauf/miniconda/envs/bertNMT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/beegfs/home/abdulrauf/miniconda/envs/bertNMT/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 118, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/mnt/beegfs/home/abdulrauf/miniconda/envs/bertNMT/lib/python3.6/site-packages/torch/nn/functional.py", line 1454, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
`

**Comment by teslacool** [comment]
I guess it is because the value of input tensor is outside the range of the embedding matrix.

Are you sure that you use the same bert model flag (--bert-model-name) to preprocess data as that you use to train NMT model?

**Comment by Binteislam** [comment]
This was the actual issue, i forgot to pass the --bert-model-name in training command. this issue solved now but following new error encountered.... 
`RuntimeError: _th_index_select is not implemented for type torch.HalfTensor`

**Comment by Binteislam** [comment]
Sorry I accidently launched the training on CPU which raised the error. Problem resolved.

Thanks for your support!!
